ALTER TABLE CFG_OUT_SYSTEM_TABLE
    RENAME COLUMN PAGE_DATA_ID TO business_id;

ALTER TABLE CFG_OUT_SYSTEM_TABLE
    RENAME COLUMN FLOW_KEY TO page_data_id;

ALTER TABLE CFG_OUT_SYSTEM_TABLE
    RENAME COLUMN FLOW_FORM_ID TO page_data_id;
