ALTER TABLE CFG_OUT_SYSTEM_TABLE
    RENAME COLUMN PAGE_DATA_ID TO BUSINESS_ID;

ALTER TABLE CFG_OUT_SYSTEM_TABLE
    RENAME COLUMN FLOW_KEY TO FLOW_FORM_ID;

ALTER TABLE CFG_OUT_SYSTEM_TABLE
    RENAME COLUMN FLOW_FORM_ID TO PAGE_DATA_ID;