ALTER TABLE CFG_PAGE_ATTACHMENT_UPLOADFILE ADD UPLOAD_TEMPLATE_FILE_ID VARCHAR2(128) NULL;
COMMENT ON COLUMN CFG_PAGE_ATTACHMENT_UPLOADFILE.UPLOAD_TEMPLATE_FILE_ID IS '上传模版文件id';

ALTER TABLE CFG_PAGE_ATTACHMENT_UPLOADFILE ADD UPLOAD_TEMPLATE_FILE_NAME VARCHAR2(512) NULL;
COMMENT ON COLUMN CFG_PAGE_ATTACHMENT_UPLOADFILE.UPLOAD_TEMPLATE_FILE_NAME IS '上传模版文件名称';