CREATE TABLE cfg_common_var
(
  id VARCHAR2(64) NOT NULL,
  field_name VARCHAR2(64),
  field_describe varchar2(200),
  cache_type varchar2(100),
  type varchar2(100),
  creator varchar2(64),
  create_time date,
  updater varchar2(64),
  update_time date,
  deleted NUMBER(1) DEFAULT 0,
  PRIMARY KEY (id)
);
comment on table cfg_common_var is '公共变量表';
comment on column cfg_common_var.id is '主键ID';
comment on column cfg_common_var.field_name is '字段名称';
comment on column cfg_common_var.field_describe is '字段描述';
comment on column cfg_common_var.cache_type is '缓存类型';
comment on column cfg_common_var.type is '前后端类型';
comment on column cfg_common_var.creator is '创建人';
comment on column cfg_common_var.create_time is '创建时间';
comment on column cfg_common_var.updater is '更新人';
comment on column cfg_common_var.update_time is '更新时间';
comment on column cfg_common_var.deleted is '是否删除';


INSERT INTO cfg_common_var (id,field_name,field_describe,cache_type,type,creator,create_time,updater,update_time,deleted) VALUES
(1872580125130678273,'ee','ee','redis','backend','1',null,'1',null,1);
INSERT INTO cfg_common_var (id,field_name,field_describe,cache_type,type,creator,create_time,updater,update_time,deleted) VALUES
(1872580158227931138,'eee','eeee','sessionStorage','frontend','1',null,'1',null,0);
INSERT INTO cfg_common_var (id,field_name,field_describe,cache_type,type,creator,create_time,updater,update_time,deleted) VALUES
(1872580188162678785,'eee','ee','redis','backend','1',null,'1',null,0);
INSERT INTO cfg_common_var (id,field_name,field_describe,cache_type,type,creator,create_time,updater,update_time,deleted) VALUES
(1872580237886152705,'2222','333','sessionStorage','frontend','1',null,'1',null,0);
INSERT INTO cfg_common_var (id,field_name,field_describe,cache_type,type,creator,create_time,updater,update_time,deleted) VALUES
(1872581244737216514,'88888','sssssssss','indexDB','frontend','1',null,'1',null,0);
INSERT INTO cfg_common_var (id,field_name,field_describe,cache_type,type,creator,create_time,updater,update_time,deleted) VALUES
(1872581309224640513,'444444444','44444','cookies','frontend','1',null,'1',null,1);
INSERT INTO cfg_common_var (id,field_name,field_describe,cache_type,type,creator,create_time,updater,update_time,deleted) VALUES
(1872585633587822593,'ddd','阿斯顿发','redis','backend','1',null,'1',null,0);
INSERT INTO cfg_common_var (id,field_name,field_describe,cache_type,type,creator,create_time,updater,update_time,deleted) VALUES
(1872585689795690498,'打发斯蒂芬','阿斯蒂芬','localStorage','frontend','1',null,'1',null,0);
INSERT INTO cfg_common_var (id,field_name,field_describe,cache_type,type,creator,create_time,updater,update_time,deleted) VALUES
(1872585755251998721,'的大是大非啊啊','阿斯顿发啊啊','redis','backend','1',null,'1',null,0);
INSERT INTO cfg_common_var (id,field_name,field_describe,cache_type,type,creator,create_time,updater,update_time,deleted) VALUES
(1891663726784913410,'curDate','当前日期','localStorage','frontend','1356921330604666888',null,'1356921330604666888',null,0);



alter table biz_hyl modify test_id default 0;
alter table biz_hyl1 modify id_test default 0;
alter table biz_sale modify deleted default 0;
alter table biz_test02 modify project default 1;
alter table cfg_app_info modify status default 0;
alter table cfg_app_info modify deleted default 0;
-- alter table cfg_backend_common_var modify deleted default 0;
alter table cfg_button_action modify deleted default 0;
alter table cfg_column_component_attribute modify tenant_id default 0;
alter table cfg_column_component_attribute modify deleted default 0;
alter table cfg_column_definition modify is_primary_key default 0;
alter table cfg_column_definition modify is_not_null default 0;
alter table cfg_column_definition modify is_auto_increment default 0;
alter table cfg_column_definition modify tenant_id default 0;
alter table cfg_column_definition modify deleted default 0;
alter table cfg_column_definition modify is_sys default 0;
alter table cfg_column_definition modify status default 0;
alter table cfg_common_model modify deleted default 0;
alter table cfg_common_var modify deleted default 0;
alter table cfg_component_attribute modify deleted default 0;
alter table cfg_component_group modify parent_id default 0;
alter table cfg_component_group modify deleted default 0;
alter table cfg_component_table modify status default 0;
alter table cfg_component_table modify deleted default 0;
alter table cfg_conditional_table modify deleted default 0;
alter table cfg_data_conversion modify deleted default 0;
alter table cfg_data_format modify thousandth default 0;
alter table cfg_data_format modify deleted default 0;
alter table cfg_db_data_domain modify deleted default 0;
alter table cfg_db_system_column modify deleted_field default 0;
alter table cfg_db_system_column modify tenant_id default 0;
alter table cfg_db_system_column modify deleted default 0;
alter table cfg_db_type_config modify tenant_id default 0;
alter table cfg_db_type_config modify deleted default 0;
alter table cfg_event_config modify deleted default 0;
alter table cfg_function_info modify parent_id default 0;
alter table cfg_function_info modify deleted default 0;
alter table cfg_index_definition modify tenant_id default 0;
alter table cfg_index_definition modify deleted default 0;
alter table cfg_log_info modify deleted default 0;
alter table cfg_module_api modify deleted default 0;
-- alter table cfg_module_api_20250205 modify deleted default 0;
alter table cfg_module_api_param modify required default 0;
alter table cfg_module_api_param modify tenant_id default 0;
alter table cfg_module_api_param modify deleted default 0;
-- alter table cfg_module_api_param_20250205 modify required default 0;
-- alter table cfg_module_api_param_20250205 modify tenant_id default 0;
-- alter table cfg_module_api_param_20250205 modify deleted default 0;
alter table cfg_module_field modify readonly default 0;
alter table cfg_module_field modify tenant_id default 0;
alter table cfg_module_field modify deleted default 0;
-- alter table cfg_module_field_0214 modify readonly default 0;
-- alter table cfg_module_field_0214 modify tenant_id default 0;
-- alter table cfg_module_field_0214 modify deleted default 0;
alter table cfg_module_info modify tenant_id default 0;
alter table cfg_module_info modify deleted default 0;
alter table cfg_module_info modify readonly default 0;
alter table cfg_module_relation_field modify tenant_id default 0;
alter table cfg_module_relation_field modify deleted default 0;
alter table cfg_module_sql modify tenant_id default 0;
alter table cfg_module_sql modify deleted default 0;
-- alter table cfg_module_sql_20250205 modify tenant_id default 0;
-- alter table cfg_module_sql_20250205 modify deleted default 0;
alter table cfg_module_table modify is_main default 0;
alter table cfg_module_table modify readonly default 0;
alter table cfg_module_table modify tenant_id default 0;
alter table cfg_module_table modify deleted default 0;
alter table cfg_out_system_table modify result_status default 0;
alter table cfg_out_system_table modify deleted default 0;
alter table cfg_page_api modify deleted default 0;
alter table cfg_page_attachment_info modify deleted default 0;
alter table cfg_page_attachment_uploadfile modify is_require default 0;
alter table cfg_page_attachment_uploadfile modify is_valid_file_name default 0;
alter table cfg_page_attachment_uploadfile modify deleted default 0;
alter table cfg_page_button modify deleted default 0;
alter table cfg_page_extend_event modify is_intercept default 0;
alter table cfg_page_extend_event modify deleted default 0;
alter table cfg_page_group modify group_sort default 0;
alter table cfg_page_group modify is_hidden default 0;
alter table cfg_page_group modify deleted default 0;
alter table cfg_page_info modify deleted default 0;
alter table cfg_page_linkage modify deleted default 0;
alter table cfg_page_list_condition modify sort default 0;
alter table cfg_page_list_condition modify deleted default 0;
alter table cfg_page_list_config modify sort default 0;
alter table cfg_page_list_config modify deleted default 0;
alter table cfg_page_parameter modify deleted default 0;
alter table cfg_paramter_list modify deleted default 0;
alter table cfg_process_design modify deleted default 0;
alter table cfg_process_node modify choice default 0;
alter table cfg_process_node modify self default 0;
alter table cfg_process_node modify def default 0;
alter table cfg_process_node modify deleted default 0;
alter table cfg_process_node_condition modify deleted default 0;
alter table cfg_process_node_event modify deleted default 0;
alter table cfg_process_node_form_property modify readonly default 0;
alter table cfg_process_node_form_property modify hidden default 0;
alter table cfg_process_node_form_property modify required default 0;
alter table cfg_process_node_form_property modify deleted default 0;
alter table cfg_process_node_permissions modify operation_value default 1;
alter table cfg_process_node_permissions modify deleted default 0;
alter table cfg_sub_table_setting modify deleted default 0;
alter table cfg_table_definition modify is_sys default 0;
alter table cfg_table_definition modify tenant_id default 0;
alter table cfg_table_definition modify deleted default 0;
alter table cfg_table_definition modify status default 0;
alter table cfg_template_content modify deleted default 0;
alter table cfg_template_group modify deleted default 0;
alter table cfg_template_info modify deleted default 0;
alter table cfg_validate_rules modify deleted default 0;
alter table infra_api_access_log modify user_id default 0;
alter table infra_api_access_log modify user_type default 0;
alter table infra_api_access_log modify operate_type default 0;
alter table infra_api_access_log modify result_code default 0;
alter table infra_api_access_log modify deleted default 0;
alter table infra_api_access_log modify tenant_id default 0;
alter table infra_api_error_log modify user_id default 0;
alter table infra_api_error_log modify user_type default 0;
alter table infra_api_error_log modify process_user_id default 0;
alter table infra_api_error_log modify deleted default 0;
alter table infra_api_error_log modify tenant_id default 0;
alter table infra_codegen_column modify deleted default 0;
alter table infra_codegen_table modify scene default 1;
alter table infra_codegen_table modify template_type default 1;
alter table infra_codegen_table modify deleted default 0;
alter table infra_config modify deleted default 0;
alter table infra_data_set_config modify deleted default 0;
alter table infra_data_set_config_http modify deleted default 0;
alter table infra_data_source_config modify deleted default 0;
alter table infra_file modify deleted default 0;
alter table infra_file_config modify deleted default 0;
alter table infra_file_content modify deleted default 0;
alter table infra_job modify retry_count default 0;
alter table infra_job modify retry_interval default 0;
alter table infra_job modify monitor_timeout default 0;
alter table infra_job modify deleted default 0;
alter table infra_job_log modify execute_index default 1;
alter table infra_job_log modify deleted default 0;
alter table log_process_data modify deleted default 0;
alter table system_dept modify parent_id default 0;
alter table system_dept modify sort default 0;
alter table system_dept modify deleted default 0;
alter table system_dept modify tenant_id default 0;
alter table system_dict_data modify sort default 0;
alter table system_dict_data modify status default 0;
alter table system_dict_data modify deleted default 0;
alter table system_dict_data_1030 modify id default 0;
alter table system_dict_data_1030 modify sort default 0;
alter table system_dict_data_1030 modify status default 0;
alter table system_dict_data_1030 modify deleted default 0;
alter table system_dict_type modify status default 0;
alter table system_dict_type modify deleted default 0;
alter table system_dict_type_1030 modify id default 0;
alter table system_dict_type_1030 modify status default 0;
alter table system_dict_type_1030 modify deleted default 0;
alter table system_login_log modify user_id default 0;
alter table system_login_log modify user_type default 0;
alter table system_login_log modify deleted default 0;
alter table system_login_log modify tenant_id default 0;
alter table system_mail_account modify ssl_enable default 0;
alter table system_mail_account modify starttls_enable default 0;
alter table system_mail_account modify deleted default 0;
alter table system_mail_log modify send_status default 0;
alter table system_mail_log modify deleted default 0;
alter table system_mail_template modify deleted default 0;
alter table system_menu modify module_type default 0;
alter table system_menu modify sort default 0;
alter table system_menu modify parent_id default 0;
alter table system_menu modify status default 0;
alter table system_menu modify visible default 1;
alter table system_menu modify keep_alive default 1;
alter table system_menu modify always_show default 1;
alter table system_menu modify deleted default 0;
alter table system_menu_20241009 modify id default 0;
alter table system_menu_20241009 modify module_type default 0;
alter table system_menu_20241009 modify sort default 0;
alter table system_menu_20241009 modify parent_id default 0;
alter table system_menu_20241009 modify status default 0;
alter table system_menu_20241009 modify visible default 1;
alter table system_menu_20241009 modify keep_alive default 1;
alter table system_menu_20241009 modify always_show default 1;
alter table system_menu_20241009 modify deleted default 0;
alter table system_notice modify status default 0;
alter table system_notice modify deleted default 0;
alter table system_notice modify tenant_id default 0;
alter table system_notify_message modify deleted default 0;
alter table system_notify_message modify tenant_id default 0;
alter table system_notify_template modify deleted default 0;
alter table system_oauth2_access_token modify deleted default 0;
alter table system_oauth2_access_token modify tenant_id default 0;
alter table system_oauth2_approve modify approved default 0;
alter table system_oauth2_approve modify deleted default 0;
alter table system_oauth2_approve modify tenant_id default 0;
alter table system_oauth2_client modify deleted default 0;
alter table system_oauth2_code modify deleted default 0;
alter table system_oauth2_code modify tenant_id default 0;
alter table system_oauth2_refresh_token modify deleted default 0;
alter table system_oauth2_refresh_token modify tenant_id default 0;
alter table system_operate_log modify user_type default 0;
alter table system_operate_log modify deleted default 0;
alter table system_operate_log modify tenant_id default 0;
alter table system_post modify deleted default 0;
alter table system_post modify tenant_id default 0;
alter table system_role modify data_scope default 1;
alter table system_role modify deleted default 0;
alter table system_role modify tenant_id default 0;
alter table system_role_20241009 modify id default 0;
alter table system_role_20241009 modify data_scope default 1;
alter table system_role_20241009 modify deleted default 0;
alter table system_role_20241009 modify tenant_id default 0;
alter table system_role_menu modify deleted default 0;
alter table system_role_menu modify tenant_id default 0;
alter table system_role_menu_20241009 modify id default 0;
alter table system_role_menu_20241009 modify deleted default 0;
alter table system_role_menu_20241009 modify tenant_id default 0;
alter table system_sms_channel modify deleted default 0;
alter table system_sms_code modify deleted default 0;
alter table system_sms_code modify tenant_id default 0;
alter table system_sms_log modify send_status default 0;
alter table system_sms_log modify receive_status default 0;
alter table system_sms_log modify deleted default 0;
alter table system_sms_template modify deleted default 0;
alter table system_social_client modify deleted default 0;
alter table system_social_client modify tenant_id default 0;
alter table system_social_user modify deleted default 0;
alter table system_social_user modify tenant_id default 0;
alter table system_social_user_bind modify deleted default 0;
alter table system_social_user_bind modify tenant_id default 0;
alter table system_tenant modify status default 0;
alter table system_tenant modify deleted default 0;
alter table system_tenant_package modify status default 0;
alter table system_tenant_package modify deleted default 0;
alter table system_user_post modify user_id default 0;
alter table system_user_post modify post_id default 0;
alter table system_user_post modify deleted default 0;
alter table system_user_post modify tenant_id default 0;
alter table system_user_role modify deleted default 0;
alter table system_user_role modify tenant_id default 0;
alter table system_user_role_20241009 modify id default 0;
alter table system_user_role_20241009 modify deleted default 0;
alter table system_user_role_20241009 modify tenant_id default 0;
alter table system_users modify sex default 0;
alter table system_users modify status default 0;
alter table system_users modify deleted default 0;
alter table system_users modify tenant_id default 0;
alter table system_users_20241009 modify id default 0;
alter table system_users_20241009 modify sex default 0;
alter table system_users_20241009 modify status default 0;
alter table system_users_20241009 modify deleted default 0;
alter table system_users_20241009 modify tenant_id default 0;
alter table test_table modify price default 0;
alter table test_table01 modify deleted default 0;
alter table trd_test_child_mysql modify is_deleted default 0;
alter table trd_test_mysql modify is_deleted default 0;
alter table yudao_demo01_contact modify deleted default 0;
alter table yudao_demo01_contact modify tenant_id default 0;
alter table yudao_demo02_category modify deleted default 0;
alter table yudao_demo02_category modify tenant_id default 0;
alter table yudao_demo03_course modify deleted default 0;
alter table yudao_demo03_course modify tenant_id default 0;
alter table yudao_demo03_grade modify deleted default 0;
alter table yudao_demo03_grade modify tenant_id default 0;
alter table yudao_demo03_student modify deleted default 0;
alter table yudao_demo03_student modify tenant_id default 0;
alter table yudao_demo03_student_address modify deleted default 0;
alter table yudao_demo03_student_address modify tenant_id default 0;
alter table yudao_demo03_teacher modify deleted default 0;
alter table yudao_demo03_teacher modify tenant_id default 0;
alter table yudao_demo03_teacher_student modify deleted default 0;
alter table yudao_demo03_teacher_student modify tenant_id default 0;

   
commit;