ALTER TABLE CFG_PROCESS_NODE ADD IS_PUSH_BACK_MODEL_DATA NUMBER(10,0) NULL;
COMMENT ON COLUMN CFG_PROCESS_NODE.IS_PUSH_BACK_MODEL_DATA IS '是否回推模型数据';

ALTER TABLE CFG_PROCESS_NODE ADD IS_PUSH_BACK NUMBER(10,0) NULL;
COMMENT ON COLUMN CFG_PROCESS_NODE.IS_PUSH_BACK IS '是否回推';


ALTER TABLE CFG_PROCESS_NODE ADD PUSH_BACK_URL VARCHAR2(128) NULL;
COMMENT ON COLUMN CFG_PROCESS_NODE.PUSH_BACK_URL IS '指定回推地址';

ALTER TABLE CFG_MODULE_INFO ADD IS_PUSH_BACK_MODEL_DATA NUMBER(10,0) NULL;
COMMENT ON COLUMN CFG_MODULE_INFO.IS_PUSH_BACK_MODEL_DATA IS '是否回推模型数据';

ALTER TABLE CFG_MODULE_INFO ADD PUSH_BACK_URL VARCHAR2(128) NULL;
COMMENT ON COLUMN CFG_MODULE_INFO.PUSH_BACK_URL IS '指定回推地址';
