ALTER TABLE CFG_MODULE_FIELD ADD IS_BACK_DATA NUMBER(10,0) NULL;
COMMENT ON COLUMN CFG_MODULE_FIELD.IS_BACK_DATA IS '是否回推';

ALTER TABLE CFG_PAGE_INFO ADD PAGE_VERSION VARCHAR2(128) NULL;
COMMENT ON COLUMN CFG_PAGE_INFO.PAGE_VERSION IS '页面版本';

ALTER TABLE CFG_MODULE_INFO ADD FLOW_LOG_PARAMS CLOB NULL;
COMMENT ON COLUMN CFG_MODULE_INFO.FLOW_LOG_PARAMS IS '流程记录回推参数';
