ALTER TABLE CFG_FILE_INFO ADD IS_PUBLIC NUMBER(10,0) NULL;
COMMENT ON COLUMN CFG_FILE_INFO.IS_PUBLIC IS '是否对外披露';
ALTER TABLE CFG_FILE_INFO ADD FILE_TITLE VARCHAR2(1000) NULL;
COMMENT ON COLUMN CFG_FILE_INFO.FILE_TITLE IS '文件标题';